GET http://localhost:8080/movie/api/show/all

###

GET http://localhost:8080/movie/api/user/all


###

DELETE http://localhost:8080/movie/api/show/delete/2

###

POST http://localhost:8080/movie/api/show/create
Content-Type: application/json

{
    "name": "Captain America",
    "duration": "2 timer",
    "location": "Sal 1",
    "startDate": "13 Juni",
    "startTime": "14:00"
  }


