GET http://localhost:8080/movie/api/show/all

###

GET http://localhost:8080/movie/api/user/all


###

DELETE http://localhost:8080/movie/api/show/delete/2

###

POST http://localhost:8080/movie/api/show/create
Content-Type: application/json

{
    "name": "Captain America",
    "duration": "2 timer",
    "location": "Sal 1",
    "startDate": "13 Juni",
    "startTime": "14:00"
  }

###

GET http://localhost:8080/movie/api/festival/all

###

DELETE http://localhost:8080/movie/api/festival/delete/3

###

POST http://localhost:8080/movie/api/festival/create
Content-Type: application/json

{
  "name": "Eksamen",
  "city": "Lyngby",
  "startDate": "13 Juni",
  "duration": "24 Timer"
}



